server:
  port: ${PORT:9630}

spring:
  application:
    name: smart-attendance-backend

  datasource:
    url: jdbc:mysql://mysql-2da9f0d6-smartattendancedb.e.aivencloud.com:28592/smart_attendance_db?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: avnadmin
    password: AVNS_8ddADGpPpVqAw2Fj-9k
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB

# JWT Config
jwt:
  secret: koi_bhi_lambi_random_string_yaha_daalo123456
  expiration-ms: 86400000

# Python AI Service URL
ai-service:
  base-url: http://localhost:8000

# File storage paths
file:
  upload-dir: ./uploads
