server:
  port: 9630

spring:
  application:
    name: smart-attendance-backend

  datasource:
    url: jdbc:mysql://localhost:3306/smart_attendance_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Sonu@9630
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update       # auto-creates/updates tables based on entities
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 200MB      # per individual video/image file
      max-request-size: 500MB   # total request size (raised to allow up to 3 videos at once)

# JWT Config
jwt:
  secret: ChangeThisToALongRandomSecretKeyForProductionUse123456789
  expiration-ms: 86400000     # 24 hours

# Python AI Service URL
ai-service:
  base-url: http://localhost:8000

# File storage paths
file:
  upload-dir: ./uploads
